#########################################################################
#                                                                       #
#    N a m e s                                                          #
#    The names of the parameters in cube in order.  	                #
#                                                                       #
#########################################################################    

names = [ 
    # Posterior weight and ChiSq - adds 2 parameters, cumalative (0)
    r'$p_i$', 
    r'$\chi^2$', 
    # Model parameters - adds 9 parameters, cumalative (2)
    r'$\alpha_s$',
    r'$m_b$ (GeV)',
    r'$1/\alpha$',
    r'tan $\beta$',
    r'$m_t$ (GeV)', 
    r'$A_0$ (GeV)',
    r'$m_{1/2}$ (GeV)', 
    r'$m_0$ (GeV)',
    r'sgn $\mu$', 
    # Predictions - 17 (11)
    r'$\alpha_s$', 
    r'$R_{hZZ}$',
    r'LHC $95\%$ bound on $m_{1/2}$ GeV',
    r'$1/\alpha$',
    r'$m_h$ (GeV)',
    r'$R_{SM}(B^+ \rightarrow \tau \nu)$',
    r'$m_b$ (GeV)', 
    r'$m_t$ (GeV)',
    r'$sin \theta$', 
    r'$M_W$ (GeV)', 
    r'$\Delta M_B$ (GeV)', 
    r'$\sigma_p^{SI}$ (fb)',
    r'$\delta a_\mu$',
    r'$\sigma * BR(h \rightarrow \gamma \gamma)$ (fb)',
    r'$b \rightarrow s \gamma$', 
    r'$\Omega h^2$', 
    r'$B_s \rightarrow \mu \mu$', 
    # chi2s  - 17 (28) 
    r'$\chi^2(\alpha_s)$', 
    r'$\chi^2(R_{hZZ})$',
    r'$\chi^2$(LHC $95\%$ bound on $m_{1/2}$)',
    r'$\chi^2(1/\alpha)$',
    r'$\chi^2(m_h)$',
    r'$\chi^2(R_{SM}(B^+ \rightarrow \tau \nu))$',
    r'$\chi^2(m_b)$', 
    r'$\chi^2(m_t)$',
    r'$\chi^2(sin_\textrm{eff} \theta)$', 
    r'$\chi^2(M_W)$', 
    r'$\chi^2(\Delta M_B)$', 
    r'$\chi^2(\sigma_p^{SI})$',
    r'$\chi^2(\delta a_\mu)$',
    r'$\chi^2(\sigma * BR(h \rightarrow \gamma \gamma))$',
    r'$\chi^2(b \rightarrow s \gamma)$', 
    r'$\chi^2(\Omega h^2)$', 
    r'$\chi^2(B_s \rightarrow \mu \mu)$', 
    # Masses from SLHA - 33 (45)
    r'$m_{\tilde{d}_R}$ (GeV)',
    r'$m_{\tilde{u}_R}$ (GeV)', 
    r'$m_{\tilde{s}_R}$ (GeV)',
    r'$m_{\tilde{c}_R}$ (GeV)',  
    r'$m_{\tilde{b}_2}$ (GeV)',  
    r'$m_{\tilde{t}_2}$ (GeV)',
    r'$m_{\tilde{e}_R}$ (GeV)', 
    r'$m_{\tilde{\mu}_R}$',
    r'$m_{\tilde{\stau}_2}$ (GeV)', 
    r'$M_W$ (GeV)', 
    r'$m_h$ (GeV)', 
    r'$m_H$ (GeV)', 
    r'$m_A$ (GeV)', 
    r'$m_{H^\pm}$ (GeV)',
    r'$m_{\tilde{d}_L}$ (GeV)',
    r'$m_{\tilde{u}_L}$ (GeV)', 
    r'$m_{\tilde{s}_L}$ (GeV)',
    r'$m_{\tilde{c}_L}$ (GeV)',  
    r'$m_{\tilde{b}_1}$ (GeV)',  
    r'$m_{\tilde{t}_1}$ (GeV)',
    r'$m_{\tilde{e}_L}$ (GeV)', 
    r'$m_{\tilde{\nu}_{e_L}$ (GeV)',
    r'$m_{\tilde{\mu}_L}$ (GeV)', 
    r'$m_{\tilde{\nu}_{\mu_L}$ (GeV)',
    r'$m_{\tilde{\stau}_1}$ (GeV)', 
    r'$m_{\tilde{\nu}_{\stau_L}$ (GeV)', 
    r'$m_{\tilde{g}}$ (GeV)',  
    r'$m_{\tilde{\chi}_1^0}$ (GeV)', 
    r'$m_{\tilde{\chi}_2^0}$ (GeV)', 
    r'$m_{\tilde{\chi}_1^\pm}$ (GeV)', 
    r'$m_{\tilde{\chi}_3^0}$ (GeV)', 
    r'$m_{\tilde{\chi}_4^0}$ (GeV)', 
    r'$m_{\tilde{\chi}_2^\pm}$ (GeV)'
    # Total 78.
    ] 
